# Generated by Django 4.1.3 on 2022-12-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='description',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_votes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='short_description',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='polls', verbose_name='Аватарка'),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
