# Generated by Django 4.1.3 on 2022-12-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_question_description_remove_question_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='polls/user', verbose_name='Аватарка'),
        ),
    ]
