# Generated by Django 4.1.3 on 2022-12-04 09:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_question_voted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='voted_by',
            field=models.ManyToManyField(blank=True, related_name='voted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='votes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
